### PR TITLE
Use SpyreTensorLayout to fill out DCIs

### LINKED ISSUE #294: Unit test test_max_sub_broadcast_cpu fails if invoking test on it specifically
### What happened?

dim=1 test fails if invoking inductor unit test with the following command
```
pytest test_inductor_ops.py -k test_max_sub
```
However this doesn't happen when invoking the full test.

### What did you expect to happen?

The test shouldn't fail when specifying `-k test_max_sub`

### How can we reproduce it?

Run the command `pytest test_inductor_ops.py -k test_max_sub` under unit test folder

### Any environmental details we need to know?

No

### Anything else we need to know?

_No response_

### Relevant log output

```Shell
(dti-venv)  (git:main)pod:~/dt-inductor/torch-spyre/tests/_inductor$ pytest test_inductor_ops.py -k test_max_sub
================================================================================================================================================= test session starts =================================================================================================================================================
platform linux -- Python 3.12.9, pytest-9.0.1, pluggy-1.6.0
rootdir: /home/ccyang/dt-inductor/torch-spyre
configfile: pyproject.toml
plugins: hypothesis-6.148.2
collected 66 items / 64 deselected / 2 selected                                                                                                                                                                                                                                                                       

test_inductor_ops.py .F                                                                                                                                                                                                                                                                                         [100%]

====================================================================================================================================================== FAILURES =======================================================================================================================================================
______________________________________________________________________________________________________________________________________ TestOps.test_max_sub_broadcast_cpu_dim_1 _______________________________________________________________________________________________________________________________________

self = <test_inductor_ops.TestOps testMethod=test_max_sub_broadcast_cpu_dim_1>, dim = 1
x = tensor([[-0.4111, -1.4902,  1.6729,  ...,  0.7002,  0.7007,  0.8647],
        [-0.1154, -1.1240,  1.0596,  ..., -0.013..., -0.5181, -1.2812],
        [-0.3916,  0.3662,  0.3760,  ..., -0.3542,  1.0820, -0.9951]],
       dtype=torch.float16)

    def test_max_sub_broadcast_cpu(self, dim: int, x):
        def fn(x):
            x_max = torch.max(x, dim=dim)[0]
            z = x - torch.unsqueeze(x_max, dim=dim)
            return z
    
>       compare_with_cpu(fn, x)  # eager mode crashes
        ^^^^^^^^^^^^^^^^^^^^^^^

test_inductor_ops.py:388: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

fn = <function TestOps.test_max_sub_broadcast_cpu.<locals>.fn at 0x7f86ab893f60>, atol = 0.1, rtol = 0.1
args = (tensor([[-0.4111, -1.4902,  1.6729,  ...,  0.7002,  0.7007,  0.8647],
        [-0.1154, -1.1240,  1.0596,  ..., -0.01...-0.5181, -1.2812],
        [-0.3916,  0.3662,  0.3760,  ..., -0.3542,  1.0820, -0.9951]],
       dtype=torch.float16),)

    def compare_with_cpu(fn, *args, atol=0.1, rtol=0.1):
        torch._dynamo.reset_code_caches()  # kernel caching workaround
        device_args = [arg.to(DEVICE) for arg in args]
        result = torch.compile(fn)(*device_args).cpu()
        cpu_result = fn(*args)
>       torch.testing.assert_close(
            result,
            cpu_result,
            equal_nan=True,
            atol=atol,
            rtol=rtol,
            msg=lambda msg: f"cpu mismatch\n\n{msg}\n",
        )
E       AssertionError: cpu mismatch
E       
E       Tensor-likes are not close!
E       
E       Mismatched elements: 22660 / 32768 (69.2%)
E       Greatest absolute difference: 8.71875 at index (124, 2) (up to 0.1 allowed)
E       Greatest relative difference: inf at index (32, 97) (up to 0.1 allowed)

utils_inductor.py:191: AssertionError

=============================================================================================================================================== short test summary info ===============================================================================================================================================
FAILED test_inductor_ops.py::TestOps::test_max_sub_broadcast_cpu_dim_1 - AssertionError: cpu mismatch
===================================================================================================================================== 1 failed, 1 passed, 64 deselected in 11.53s =====================================================================================================================================
```

### PR DESCRIPTION
**Pull request by avery-blanchard**
Thanks for sending a pull request! Please make sure you read the [contributing guidelines](https://github.com/torch-spyre/torch-spyre/blob/main/CONTRIBUTING.md).

#### What type of PR is this?

- [ ] bug
- [x] feature
- [ ] documentation
- [ ] cleanup

#### What this PR does:
This PR uses SpyreTensorLayout to fill out data conversions before/after data transfers. This implements `spyre_empty_with_layout` to enable Inductor to fill out custom layouts. This also implements `spyre_empty`, which previously used the generic implementation, to create tensors with `SpyreTensorImpl`. The default generic stick layout is used for tensors created without a specified SpyreTensorLayout. 

An eager test (`test_t_1d`) has a tensor that does not go through `spyre_empty`, `spyre_empty_strided` nor `spyre_as_strided`. This test is temporarily skipped until an operation is added support these tensor views with SpyreTensorImpls. 

#### Which issue(s) this PR is related to:

Fixes #294 #104 #105

#### Additional note:
image

### CODE REVIEW

File: torch_spyre/csrc/spyre_mem.cpp [hunk 1]
```diff
@@ -597,9 +500,32 @@ at::Tensor spyre_empty(c10::IntArrayRef size,
   TORCH_CHECK(!c10::pinned_memory_or_default(pin_memory_opt),
               "Pin memory can only be on CPU");
   const c10::DeviceGuard device_guard(device);
+  // Check if tensor requires padding
+  int stick_size = BYTES_IN_STICK / c10::elementSize(dtype);
```
Comment (dgrove-oss) [inline torch_spyre/csrc/spyre_mem.cpp]: Same comment here.   c10::elementSIze is going to be wrong for boolean.

**Review by dgrove-oss — COMMENTED** [review]
I think there are a few places where we need to use the device element type to figure out the number of elements in a stack.  Otherwise looks good.

**Review by dgrove-oss — APPROVED** [review]
lgtm

File: tests/tensor/test_tensor_layout.py [hunk 2]
```diff
@@ -40,9 +40,9 @@ def test_generic_stick(self):
         self.assertEqual(stl.num_stick_dims, 1)
 
         stl = SpyreTensorLayout([512, 8, 256], torch.float16)
-        self.assertEqual(stl.device_size, [512, 4, 8, 64])
-        self.assertEqual(stl.device_strides(), [2048, 512, 64, 1])
-        self.assertEqual(stl.dim_map, [0, 2, 1, 2])
+        self.assertEqual(stl.device_size, [8, 4, 512, 64])
```
Comment (thoangtrvn) [inline tests/tensor/test_tensor_layout.py]: would it be possible to provide an explanation for the change in test input data?

File: tests/test_ops.py [hunk 3]
```diff
@@ -119,6 +119,7 @@ def test_copy_4d(self):
         y = x.to("spyre").to("cpu")
         torch.testing.assert_close(y, x, rtol=self.rtol, atol=self.atol)
 
+    @unittest.skip("View tensors do not have SpyreTensorImpl")
```
Comment (thoangtrvn) [inline tests/test_ops.py]: Could you help to clarify why this test is skipped now? Did the test run successfully before this PR?

**Review by thoangtrvn — COMMENTED** [review]
The PR disables one test. Would you be able to maintain the functionality of the test or explain why it should be disabled and if so, is there a plan to reenable it?

File: tests/test_ops.py (hunk 3 above)
Comment (thoangtrvn) [reply tests/test_ops.py]: @avery-blanchard : as we discussed, could you create a new issue and add a reference from here so that we know what need to be done?
